### ISSUE TITLE
Member 엔티티의 Password 를 nullable 하게 변경

### ISSUE THREAD

**Issue by ParkJiwoon** [Project-DC-Inside/dcinside-server#10]
비회원은 회원가입 없이 비회원 토큰을 `username` 으로 등록해서 사용합니다.

이 때 별도의 `password` 는 사용하지 않으므로 nullable 하게 세팅합니다.

**Comment by DolphaGo** [comment]
생각해보니 비회원 관리를 하려면
페이지 진입시에 바로 가입이 되어야 하는 구조군요.

그러면 디바이스마다 저희 페이지에 진입할 때마다 계속 가입이 되겠네요.
즉, **진입하는 시점에 가입 및 accessToken, refreshToken을 내어주는 형태**

즉, 정상적인 가입 절차가 이뤄질 때 1명당 최소 2개의 row를 차지하겠네요.

디바이스별로 회원을 관리한다는 점은 조금 아쉽긴 하군요.. 비회원 관리하는 것은 과연 이 방법밖에 없는 걸까요. 흐음..

**Comment by ParkJiwoon** [comment]
슬랙에서도 말했지만 비회원이 필요한 이유가 단순히 푸시 알림을 위한 거라서 FCM 스펙에 따라 나중에 변경해야 할 수도 있을 것 같네요
디바이스에서 내가쓴글, 내가쓴댓글 이런거는 14일만 보관하기 때문에 굳이 서버에 저장하지 않고 클라에서 관리할 수 있을겁니다

**Comment by ParkJiwoon** [comment]
비회원 스펙을 폐지함에 따라서 이 이슈도 닫겠습니다.
Reference: https://github.com/Project-DC-Inside/logs/issues/1#issuecomment-1032567646
