### ISSUE TITLE
API 의 결과값 중 result 는 무조건 JSON 형식으로 내려주기

### ISSUE THREAD

**Issue by ParkJiwoon** [Project-DC-Inside/dcinside-server#23]
게시글 생성, 댓글 생성 등은 `Long` 타입으로 내려주는데 클라이언트 입장에서 어떤 값인지 한눈에 알기 어려움

**Comment by ParkJiwoon** [comment]
+) 추가로 어차피 클라에서 생성 요청 후의 id 값을 사용하지 않으므로 내려주지 않도록 변경

**Comment by unluckyjung** [comment]
히스토리 관리용: https://deep-foresthq.slack.com/archives/C02NSTG4QQL/p1652196852157419
